name: Create Release

on:
  push:
    tags:
    - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2


      - name: Create release name using the tag name
        run: |
             githubRef=${{ github.ref }}
             githubRef="${githubRef/'refs/tags'/''}"
             githubRef="${githubRef/'/'/''}"
             githubRef="${githubRef/'v'/''}"
             echo "releaseLabel=$githubRef" >> $GITHUB_ENV             


      - name: Print release label
        run: echo $releaseLabel 


      - name: Create temp directory
        run: mkdir temp


      - name: Create release directory
        run: mkdir release


      - name: Combine javascript files into a single file 
        run: find ./src -name '*.js' -exec cat {} \; > ./temp/javaxt-webcontrols.js


      - name: Minify the combined file
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: ./temp
          output: ./release
          overwrite: true


      - name: Prepend release info to minified file
        run: |
             sudo chmod 777 ./release/javaxt-webcontrols.js
             printf '%s\n%s\n' "//javaxt-webcontrols ${{ env.releaseLabel }}" "$(cat ./release/javaxt-webcontrols.js)" >./release/javaxt-webcontrols.js


      - name: Copy release assets to the release directory
        run: cp -r src demos themes LICENSE.TXT release


      - name: Create zip file
        run: cd release; zip -r ../javaxt-webcontrols_v${{ env.releaseLabel }}.zip *        


      - name: Upload release to server
        run: >-
          curl -X POST -L 
          -H "Authorization: ${{ secrets.UPLOAD_AUTH }}" 
          -F "file=@javaxt-webcontrols_v${{ env.releaseLabel }}.zip;type=application/zip" 
          "${{ secrets.UPLOAD_URL }}"
          
